import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'appTitle': "SureVote",
      'about': "About SureVote",
      'description': "A secure online voting platform using face recognition.",
      'changeLanguage': "Change Language",
      'selectLanguage': "Select Language",
      'secureVoting': "Secure Face Recognition",
      'oneVote': "One-Vote-Per-User Restriction",
      'realTime': "Real-Time Dashboard",
      'otp': "OTP Authentication (Future Scope)",
      'multiLang': "Multi-Language Support",
    },
    'hi': {
      'appTitle': "सुरवोट",
      'about': "सुरवोट के बारे में",
      'description': "फेस रिकग्निशन का उपयोग करने वाला एक सुरक्षित ऑनलाइन मतदान प्लेटफ़ॉर्म।",
      'changeLanguage': "भाषा बदलें",
      'selectLanguage': "भाषा चुनें",
      'secureVoting': "सुरक्षित चेहरा पहचान",
      'oneVote': "प्रति उपयोगकर्ता केवल एक वोट",
      'realTime': "रीयल-टाइम डैशबोर्ड",
      'otp': "ओटीपी प्रमाणीकरण (भविष्य की योजना)",
      'multiLang': "बहु-भाषा समर्थन",
    },
    'ur': {
      'appTitle': "سور ووٹ",
      'about': "سور ووٹ کے بارے میں",
      'description': "چہرے کی پہچان استعمال کرنے والا محفوظ آن لائن ووٹنگ پلیٹ فارم۔",
      'changeLanguage': "زبان تبدیل کریں",
      'selectLanguage': "زبان منتخب کریں",
      'secureVoting': "محفوظ چہرہ شناخت",
      'oneVote': "فی صارف ایک ووٹ",
      'realTime': "ریئل ٹائم ڈیش بورڈ",
      'otp': "او ٹی پی تصدیق (مستقبل کی گنجائش)",
      'multiLang': "کثیر زبان کی حمایت",
    },
    'bn': {
      'appTitle': "সুরভোট",
      'about': "সুরভোট সম্পর্কে",
      'description': "ফেস রেকগনিশন ব্যবহার করে একটি নিরাপদ অনলাইন ভোটিং প্ল্যাটফর্ম।",
      'changeLanguage': "ভাষা পরিবর্তন করুন",
      'selectLanguage': "ভাষা নির্বাচন করুন",
      'secureVoting': "নিরাপদ মুখের স্বীকৃতি",
      'oneVote': "প্রতি ব্যবহারকারী এক ভোট",
      'realTime': "রিয়েল-টাইম ড্যাশবোর্ড",
      'otp': "ওটিপি প্রমাণীকরণ (ভবিষ্যতের সুযোগ)",
      'multiLang': "একাধিক ভাষার সমর্থন",
    },
    'ta': {
      'appTitle': "சுர்வோட்",
      'about': "சுர்வோட் பற்றி",
      'description': "முகஅடையாளத்தைப் பயன்படுத்தி பாதுகாப்பான ஆன்லைன் வாக்குச்சீட்டு தளம்.",
      'changeLanguage': "மொழி மாற்று",
      'selectLanguage': "மொழியைத் தேர்ந்தெடுக்கவும்",
      'secureVoting': "பாதுகாப்பான முகஅடையாளம்",
      'oneVote': "ஒரு பயனருக்கு ஒரு வாக்கு மட்டுமே",
      'realTime': "நிகழ்நிலை டாஷ்போர்ட்",
      'otp': "OTP உறுதிப்படுத்தல் (எதிர்காலத்திற்கான திட்டம்)",
      'multiLang': "பன்மொழி ஆதரவு",
    },
  };
}
